Sender: LSF System <lsfadmin@eu-c7-024-05>
Subject: Job 63309153: < # This script tries out different window sizes and sends a job to the Euler-cluster which;# does RandomSearchCV for all classifiers; # for gradient_w in 2 5 10 30;# do;#     for hw in 2  10 30 60;#     do;#         for cw in 2  10 30 60;#         do;#             for (( clf_idx=0; clf_idx <=6; clf_idx ++));#             do;#                 bsub -W 100:00 -N 'python "$PWD"/main_grid_search.py $clf_idx 200 $hw $cw gradient_w';#             done;  for gradient_w in 2 5 10;do;    for hw in 2 10 30 60;    do;        for cw in 2 10 30 60;        do;            python "$PWD"/window_optimization.py $hw $cw $gradient_w;        done;    done;done> in cluster <euler> Exited

Job < # This script tries out different window sizes and sends a job to the Euler-cluster which;# does RandomSearchCV for all classifiers; # for gradient_w in 2 5 10 30;# do;#     for hw in 2  10 30 60;#     do;#         for cw in 2  10 30 60;#         do;#             for (( clf_idx=0; clf_idx <=6; clf_idx ++));#             do;#                 bsub -W 100:00 -N 'python "$PWD"/main_grid_search.py $clf_idx 200 $hw $cw gradient_w';#             done;  for gradient_w in 2 5 10;do;    for hw in 2 10 30 60;    do;        for cw in 2 10 30 60;        do;            python "$PWD"/window_optimization.py $hw $cw $gradient_w;        done;    done;done> was submitted from host <eu-login-07> by user <morathba> in cluster <euler> at Tue May  8 14:45:36 2018.
Job was executed on host(s) <eu-c7-024-05>, in queue <normal.4h>, as user <morathba> in cluster <euler> at Tue May  8 14:46:29 2018.
</cluster/home/morathba> was used as the home directory.
</cluster/home/morathba/Code/plunder-planet/ML Model> was used as the working directory.
Started at Tue May  8 14:46:29 2018.
Terminated at Tue May  8 15:53:58 2018.
Results reported at Tue May  8 15:53:58 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input

# This script tries out different window sizes and sends a job to the Euler-cluster which
# does RandomSearchCV for all classifiers

# for gradient_w in 2 5 10 30
# do
#     for hw in 2  10 30 60
#     do
#         for cw in 2  10 30 60
#         do
#             for (( clf_idx=0; clf_idx <=6; clf_idx ++))
#             do
#                 bsub -W 100:00 -N 'python "$PWD"/main_grid_search.py $clf_idx 200 $hw $cw gradient_w'
#             done


for gradient_w in 2 5 10
do
    for hw in 2 10 30 60
    do
        for cw in 2 10 30 60
        do
            python "$PWD"/window_optimization.py $hw $cw $gradient_w
        done
    done
done

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   4001.36 sec.
    Max Memory :                                 230 MB
    Average Memory :                             185.11 MB
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               794.00 MB
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                6
    Run time :                                   4062 sec.
    Turnaround time :                            4102 sec.

The output (if any) follows:

/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py:313: RankWarning: Polyfit may be poorly conditioned
  slope, _ = np.polyfit(last_x_seconds_df['Time'], last_x_seconds_df['Heartrate'], 1)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 57, in get_feature_matrix_and_label
    matrix['std_hr'] = get_standard_feature('std', 'Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 121, in get_standard_feature
    hr_df = get_column(list_idx, feature, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 241, in get_column
    return gl.obstacle_df_list[idx].apply(compute, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 239, in compute
    return res if not math.isnan(res) else compute(df.iloc[1])
  [Previous line repeated 960 more times]
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 215, in compute
    last_x_seconds_df = df_from_to(max(0, row['Time'] - window), row['Time'], df)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 186, in df_from_to
    mask = (_from <= df['Time']) & (df['Time'] < _to)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 939, in wrapper
    other = fill_int(other) if is_other_int_dtype else fill_bool(other)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/ops.py", line 932, in <lambda>
    fill_bool = lambda x: x.fillna(False).astype(bool)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 600, in _astype
    return self.copy()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 737, in copy
    return self.make_block_same_class(values)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 224, in make_block_same_class
    fastpath=fastpath, **kwargs)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/internals.py", line 114, in __init__
    self.mgr_locs = placement
RecursionError: ('maximum recursion depth exceeded', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 30')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 23')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 65, in get_feature_matrix_and_label
    matrix['hr_gradient_changes'] = get_number_of_gradient_changes('Heartrate')
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 165, in get_number_of_gradient_changes
    changes = get_gradient_changes_column(list_idx, data_name)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 357, in get_gradient_changes_column
    return gl.obstacle_df_list[idx].apply(compute_gradient_changes, axis=1)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 349, in compute_gradient_changes
    gradx = np.gradient(data)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/numpy/lib/function_base.py", line 1756, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: ('Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.', 'occurred at index 11')
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Init dataframes...
Dataframe not cached. Creating dataframe...
Normalize hr...
Compute crashes...
Dataframe created
Creating feature matrix...

Creating mean_Heartrate feature...
Creating std_Heartrate feature...
Creating max_minus_min_Heartrate feature...
Creating lin_regression_hr_slope feature...
Creating Heartrate_gradient_changes feature...
Creating %crashes feature...
Creating mean_Points feature...
Creating std_Points feature...
Traceback (most recent call last):
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/window_optimization.py", line 55, in <module>
    X, y = f_factory.get_feature_matrix_and_label()
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/features_factory.py", line 102, in get_feature_matrix_and_label
    plots.plot_correlation_matrix(matrix)
  File "/cluster/home/morathba/Code/plunder-planet/ML Model/plots.py", line 32, in plot_correlation_matrix
    plt.subplots(figsize=(len(f_factory.feature_names), len(f_factory.feature_names)))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
